basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: Servicio de autenticaci√≥n para registro y login de usuarios
  title: Auth Service API
  version: "1.0"
paths: {}
swagger: "2.0"
